spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/Board
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.Board.domain